apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: char-agent
  name: char-agent
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: char-agent
  template:
    metadata:
      labels:
        app: char-agent
    spec:
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: GPU_LIST
          value: '[{''GPU_name'': ''NVIDIA Corporation AD107M [GeForce RTX 4050 Max-Q
            / Mobile] (rev a1) (prog-if 00 [VGA controller])'', ''id'': 1, ''quantity'':
            1}]'
        - name: DEVICE_MODEL
          value: Lenovo LOQ 15ARP9
        image: gkorod/char-agent:v1.2
        imagePullPolicy: Always
        name: char-agent
        ports:
        - containerPort: 5001
          name: char-agent
        securityContext:
          privileged: true
      hostNetwork: true
      imagePullSecrets:
      - name: charagent
