apiVersion: v1
kind: Service
metadata:
  name: monitorable-char-agent
  namespace: monitoring
  labels:
    app: char-agent-service
spec:
  ports:
  - name: metrics
    targetPort: 5001
    port: 5001
  selector:
    app: char-agent
