apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitorable-char-agent
  namespace: monitoring
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: char-agent-service
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics
      interval: 120s