apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: blackbox-icmp-nodes-master
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    params:
      module:
      - icmp
    path: /probe
    port: http
    relabelings:
    - replacement: 147.102.19.170
      sourceLabels: []
      targetLabel: __param_target
    - sourceLabels:
      - __param_target
      targetLabel: instance
    - sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: source_node
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: blackbox-exporter-master
