apiVersion: v1
kind: Service
metadata:
  labels:
    app: blackbox-exporter-master
  name: blackbox-exporter-master-service
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9115
    targetPort: http
  selector:
    app: blackbox-exporter-master
