apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox-icmp-nodes
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: blackbox-exporter-master
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http
      path: /probe
      interval: 30s
      params:
        module:
          - icmp
