apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: monitoring-api
  name: monitoring-api
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: monitoring-api
  template:
    metadata:
      labels:
        app: monitoring-api
    spec:
      containers:
      - env:
        - name: ECHOSERVER_IP
          value: ''
        - name: MASTER_IP
          value: 192.168.1.3
        - name: KAFKA_IP
          value: continuum.accordion-project.eu:9092
        - name: RID_IP
          value: ''
        - name: PROMETHEUS_IP
          value: 10.43.97.251:9090
        - name: MINICLOUD_ID
          value: ''
        image: gkorod/monitoringapi:v1.0
        imagePullPolicy: Always
        name: monitoring-api
        volumeMounts:
        - mountPath: /root/
          name: .config
      hostNetwork: true
      imagePullSecrets:
      - name: api
      nodeSelector:
        beta.kubernetes.io/os: linux
        monitoringMaster: 'true'
      volumes:
      - hostPath:
          path: /home/giannis/EdgeCloud-Mon/monitoring_installation/config
          type: Directory
        name: config
