apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: prometheus-pv-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /opt/Prometheus/prometheus/
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
