apiVersion: v1
kind: Service
metadata:
  name: monitorable-vm-windows-exporter
  namespace: accordion-ovr-0-0-3-123
  labels:
    app: monitorable-vm-windows-exporter
spec:
  ports:
  - name: metrics
    targetPort: 9182
    port: 9182
  selector:
    app: monitorable-vm-windows-exporter
