apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitorable-vm-windows-exporter
  namespace: monitoring
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: monitorable-vm-windows-exporter
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics
      interval: 60s